<?php 
// notice error : notice is a minor error that will generated by users
// $name="Yash kumar";
// echo $nameen; //undefined
// $name="hi";
// echo $name4;

// $a="Defined error";
// echo "Notice error";
// echo $b;

// report an error
error_reporting(0);

$name="yash kumar";
//echo "notice error";
echo $name;


?>